#!/bin/sh

#
# A wrapper script for Blender
#
# orginal file for Debian distribution

# In case user's home directory doesn't contain ~/.blender, copy it
# from /usr/lib/blender

if [ ! -d ~/.blender ]; then
    install -d ~/.blender
    ln -sf /usr/share/blender/locale ~/.blender
    ln -sf /usr/share/blender/.Blanguages ~/.blender
    ln -sf /usr/share/blender/.bfont.ttf ~/.blender
    cp -a /usr/share/blender/bpydata ~/.blender
    cp -a /usr/share/blender/VERSION ~/.blender

    install -d ~/.blender/scripts
    ln -sf /usr/share/blender/scripts/* ~/.blender/scripts/

    install -d ~/.blender/plugins/

    if [ ! -d /usr/lib/blender ]; then
	ln -sf /usr/lib64/blender/plugins/* ~/.blender/plugins/
    else
	ln -sf /usr/lib/blender/plugins/* ~/.blender/plugins/
    fi
    

fi

# 
# In case the user's ~/.blender came from older versions, some files 
# should be reinstalled.
#

if [ $(cat ~/.blender/VERSION) != $(cat /usr/share/blender/VERSION) ]; then
    cp -a /usr/lib/blender/bpydata ~/.blender
    ln -sf /usr/lib/blender/scripts/* ~/.blender/scripts/
    cp -a /usr/lib/blender/VERSION ~/.blender
fi

blender-bin $@

